version: "3.8"

services:
  releaser:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-openswoolebundle}/${IMAGE:-release-version-script}:${TAG:-local}"
    build:
      context: .
      args:
        NODE_TAG: "${NODE_VERSION:-20}-alpine${ALPINE_VERSION:-3.18}"
    environment:
      DEBUG: "${DEBUG:-1}"
      DRY_RUN: "${DRY_RUN:-1}"
      GH_REPOSITORY: "${GH_REPOSITORY:-openswoole-bundle/release-version-script}"
      GH_COMMITER_NAME: "${GH_COMMITER_NAME:-openswoole-bundle-bot}"
      GH_COMMITER_EMAIL: "${GH_COMMITER_EMAIL:-147276322+openswoole-bundle-bot@users.noreply.github.com}"
      GH_TOKEN: "${GH_TOKEN:-xxxxxxxx}"
      GH_RELEASE_DRAFT: "${GH_RELEASE_DRAFT:-true}"
      GH_RELEASE_PRERELEASE: "${GH_RELEASE_PRERELEASE:-false}"
    volumes:
      - "./.git:/usr/src/app/.git:rw"
      - "./CHANGELOG.md:/usr/src/app/CHANGELOG.md:rw"
      - "./release-version.sh:/usr/local/bin/release-version:rw"
